version: '3.1'
services:
  mysql-service:
    container_name: rh-mysql
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gestion_rh_rest
      MYSQL_USER: manager_rh_1
      MYSQL_PASSWORD: 123456789
    ports:
      - "8090:3306"

  rh-manager:
    build:
      context: .
    container_name: rh-app
    volumes:
      - .:/app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-service
